export const products = [
  {
    id: 1,
    name: "SILK NIGHT SLIP",
    price: 4900,
    images: ["/product1.jpg", "/product2.jpg"],
    description:
      "A whisper-light slip crafted from pure mulberry silk. Falls effortlessly at mid-thigh with delicate adjustable straps and a barely-there lace trim at the hem.",
    details: ["100% Mulberry Silk", "Adjustable spaghetti straps", "Lace trim hem", "Hand wash cold"],
    sizes: ["XS", "S", "M", "L", "XL"],
    fabric: "Silk",
    color: "Blush",
    colorHex: "#e8c4b8",
    tag: "New In",
  },
  {
    id: 2,
    name: "VELVET ROBE",
    price: 6200,
    images: ["/product3.jpg", "/product4.jpg"],
    description:
      "Envelop yourself in the soft weight of crushed velvet. A generous tie-waist and wide lapels make this robe as elegant as it is comfortable.",
    details: ["95% Viscose, 5% Elastane", "Tie waist belt", "Two side pockets", "Dry clean only"],
    sizes: ["XS", "S", "M", "L", "XL"],
    fabric: "Velvet",
    color: "Noir",
    colorHex: "#2a2a2a",
    tag: "Best Seller",
  },
  {
    id: 3,
    name: "LACE TRIM SET",
    price: 5500,
    images: ["/product5.jpg", "/product6.jpg"],
    description:
      "A matched camisole and short set trimmed in Chantilly lace. The blush-toned fabric drapes softly and moves with you through the night.",
    details: ["Modal & Lace blend", "Matching cami + shorts", "Elasticated waist", "Machine wash gentle"],
    sizes: ["XS", "S", "M", "L"],
    fabric: "Modal",
    color: "Blush",
    colorHex: "#e8c4b8",
    tag: "New In",
  },
  {
    id: 4,
    name: "SATIN PYJAMA",
    price: 5100,
    images: ["/product7.jpg", "/product8.jpg"],
    description:
      "Classic pyjama tailoring reimagined in liquid satin. Notch collar, mother-of-pearl buttons, and a relaxed trouser with contrast piping.",
    details: ["100% Satin Polyester", "Button front top", "Wide-leg trousers", "Machine wash cold"],
    sizes: ["XS", "S", "M", "L", "XL"],
    fabric: "Satin",
    color: "Ivory",
    colorHex: "#f5f0e8",
    tag: null,
  },
  {
    id: 5,
    name: "MODAL LOUNGE SET",
    price: 4600,
    images: ["/product9.jpg", "/product10.jpg"],
    description:
      "Second-skin softness in the finest micro-modal. A relaxed long-sleeve top pairs with tapered lounge trousers, perfect for slow mornings.",
    details: ["96% MicroModal, 4% Elastane", "Relaxed crop top", "Tapered trousers", "Machine wash cold"],
    sizes: ["S", "M", "L", "XL"],
    fabric: "Modal",
    color: "Stone",
    colorHex: "#b5a99a",
    tag: null,
  },
  {
    id: 6,
    name: "GAUZE NIGHTDRESS",
    price: 3900,
    images: ["/product11.jpg", "/product12.jpg"],
    description:
      "A free-flowing nightdress in double-layered cotton gauze. Smocked at the yoke and tied at the back, effortlessly romantic for warm nights.",
    details: ["100% Cotton Gauze", "Smocked yoke detail", "Back tie closure", "Machine wash warm"],
    sizes: ["XS", "S", "M", "L", "XL"],
    fabric: "Cotton",
    color: "Ivory",
    colorHex: "#f5f0e8",
    tag: "Best Seller",
  },
  {
    id: 7,
    name: "SILK KIMONO ROBE",
    price: 7200,
    images: ["/product1.jpg", "/product3.jpg"],
    description:
      "A floor-length kimono robe in weighted crepe silk. Oversized sleeves, an obi-inspired sash, and hand-rolled edges throughout.",
    details: ["100% Crepe Silk", "Floor length", "Obi sash belt", "Dry clean only"],
    sizes: ["XS", "S", "M", "L"],
    fabric: "Silk",
    color: "Noir",
    colorHex: "#2a2a2a",
    tag: "Limited",
  },
  {
    id: 8,
    name: "CASHMERE LOUNGE TOP",
    price: 8100,
    images: ["/product5.jpg", "/product7.jpg"],
    description:
      "Impossibly soft cashmere in a relaxed ribbed knit. A versatile lounge top that moves effortlessly from bedroom to breakfast table.",
    details: ["100% Grade A Cashmere", "Ribbed knit", "Drop shoulder", "Hand wash cold"],
    sizes: ["S", "M", "L", "XL"],
    fabric: "Cashmere",
    color: "Stone",
    colorHex: "#b5a99a",
    tag: "New In",
  },
];